### ISSUE TITLE
Not able to run collectstatic

### ISSUE THREAD

**Issue by jeavanderwiel** [lemonsaurus/django-simple-bulma#82]
Hi, 

When I followed all the steps and I need to run the following command: python manage.py collectstatic

I get this error message:

`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 155, in handle
    self.check(tags=[Tags.staticfiles])
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/contrib/staticfiles/checks.py", line 7, in check_finders
    for finder in get_finders():
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 282, in get_finders
    yield get_finder(finder_path)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/contrib/staticfiles/finders.py", line 291, in get_finder
    Finder = import_string(import_path)
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/joshua/.pyenv/versions/3.7.2/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/joshua/Documents/Code/SHOP/saulgadgets/env/lib/python3.7/site-packages/django_simple_bulma/finders.py", line 166
    if absolute_path := finder.find(relative_path):
                      ^
SyntaxError: invalid syntax`

Could somebody help me with this please.

Thank you!

Kind regards,

Joshua

**Comment by Akarys42** [comment]
Hi. You are running Python 3.7, while this version of simple bulma requires 3.8. You need to either upgrade your Python version or downgrade simple bulma.

**Comment by jeavanderwiel** [comment]
> Hi. You are running Python 3.7, while this version of simple bulma requires 3.8. You need to either upgrade your Python version or downgrade simple bulma.

Thank you Akarys42, this solved indeed my problem!
