### ISSUE TITLE
Bulma-Calendar sass import fails with django-simple-bulma-2.5.0

### ISSUE THREAD

**Issue by bpepple** [lemonsaurus/django-simple-bulma#85]
Updated to django-simple-bulma-2.5.0 and get the following error.

```
(metron) bpepple@frodo ~/git/metron (deps) $ python3 manage.py check
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/management/base.py", line 373, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/management/base.py", line 417, in execute
    output = self.handle(*args, **options)
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/management/commands/check.py", line 63, in handle
    self.check(
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/management/base.py", line 438, in check
    all_issues = checks.run_checks(
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django/core/checks/registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/debug_toolbar/apps.py", line 108, in check_panel_configs
    for check_message in panel_class.run_checks():
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/debug_toolbar/panels/staticfiles.py", line 193, in run_checks
    for path, finder_storage in finder.list([]):
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django_simple_bulma/finders.py", line 215, in list
    files = self._get_bulma_css()
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django_simple_bulma/finders.py", line 143, in _get_bulma_css
    css_string = sass.compile(string=scss_string,
  File "/home/bpepple/.local/share/virtualenvs/metron-UZX73b7p/lib64/python3.8/site-packages/sass.py", line 738, in compile
    raise CompileError(v)
sass.CompileError: Error: File to import not found or unreadable: ~bulma/sass/utilities/functions.sass.
        on line 1:1 of ../../.local/share/virtualenvs/metron-UZX73b7p/lib/python3.8/site-packages/django_simple_bulma/extensions/bulma-calendar/src/sass/index.sass
        from line 12:1 of stdin
>> @import "~bulma/sass/utilities/functions.sass";
```

**Comment by lemonsaurus** [comment]
Interesting! I'll investigate. Recommend you use 2.4.0 until then.

Probably a result of bumping the extensions to the latest version.

**Comment by shivan-s** [comment]
Ran into the same issue as well. :'(

I wish I could help.

**Comment by lemonsaurus** [comment]
This is like 4 major versions ago so I'll close it for now.
